server:
  port: 9521
  servlet:
      context-path: /nl-pm-server
spring:
  profiles:
    active: @profile.active@
  application:
    name: nl-pm-server
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    maxActive: 20
    minIdle: 5
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    poolPreparedStatements: true
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1 FROM DUAL
    #url username password 见子配置文件

mybatis-plus:
  mapper-locations: classpath*:com/nl/pm/server/registry/dao/*.xml
  type-aliases-package: com.nl.pm.server.registry.entity
  configuration:
    #    自动驼峰命名
    db-column-underline: true
    map-underscore-to-camel-case: true
    # 打印 sql log-impl 见子配置文件
  global-config:
    db-config:
      id-type: ASSIGN_ID



#showSql
logging:
  config: classpath:logback-spring.xml

jwt:
  expireDateTime:  86400000  # 1000*60*60*24


system:
  domainName: 'http://daily.nltd.com.cn:8088'
  syncProjectSystemSendEmail: 'dayreportsystem3@nltd.com.cn'
  syncProjectSystemSendEmailHost: 'smtp.ym.163.com'
  syncProjectSystemSendEmailPassword: 'Taylor2008'
  # crmProjectSyncUrl       见子配置文件
  # syncProjectManagerEmail 见子配置文件
  # syncProjectManagerName  见子配置文件
  send:
    email:
      nickname: nl