spring:
  datasource:
    url: 'jdbc:mysql://192.168.123.241:30007/nl_pm_server?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true'
    username: 'root'
    password: 'Heroic'
  second-datasource:
    url: 'jdbc:mysql://192.168.123.241:30007/cfapp_dms?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true'
    username: 'root'
    password: 'Heroic'

mybatis-plus:
  configuration:
    # 打印 sql
    log-impl: 'org.apache.ibatis.logging.stdout.StdOutImpl'

system:
  crmProjectSyncUrl: 'http://192.168.123.71:8089/ADInterface/services/project/service/get'
  syncProjectManagerEmail: 'rhzhang@nltechdev.com'
  syncProjectManagerName: '张瑞晗'
